[package]
name = "all-smi"
version = "0.2.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
crossterm = "0.28.1"
clap = { version = "4.5.4", features = ["derive"] }
axum = "0.7.5"
tower-http = { version = "0.5.2", features = ["cors", "trace"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
regex = "1"

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.29"
objc = "0.2"
