[package]
name = "all-smi"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
crossterm = "0.28.1"

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.29"
objc = "0.2"
